### ISSUE TITLE
3.30.0 Fatal Exception: "java.lang.IllegalStateException: Android TV ads library should be called from an Android TV app"

### ISSUE THREAD

**Issue by AndreyPogorely** [googleads/googleads-ima-android-dai#67]
3.30.0 crashes with `java.lang.IllegalStateException: Android TV ads library should be called from an Android TV app` when any video is played. We see this issue in the sample app and when we try to use `3.30.0` in our apps (Paramount).

Repro steps:
1. Download and build Advanced Example from the latest Google Ads IMA SDK Android Examples
2. Update the `app/build.gradle` to use `3.30.0`
3. Play any video

App crashes with:
```
FATAL EXCEPTION: pool-1-thread-3 
   Process: com.google.ads.interactivemedia.v3.samples.videoplayerapp, PID: 23471
     java.lang.IllegalStateException: Android TV ads library should be called from an Android TV app
       at com.google.android.gms.internal.atv_ads_framework.zzd.zzb(com.google.android.tv:tv-ads@@1.0.0-alpha01:27)
       at com.google.android.tv.ads.zzg.run(com.google.android.tv:tv-ads@@1.0.0-alpha01:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

Devices: Samsung-SM-G935A (API 26), FireHD8, FireStick.

**Comment by AndreyPogorely** [comment]
[build.gradle.txt](https://github.com/googleads/googleads-ima-android-dai/files/11153741/build.gradle.txt)
